AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3BuildBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
        BucketName: 'iac-demo-build-bucket-s3'
        AccessControl: Private
        VersioningConfiguration:
          Status: Suspended
        Tags:
          - Key: Name
            Value: 'iac-demo-build-bucket-s3'
  CBProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: iac-demo-codebuild-project
      Description: iac-demo-codebuild-project
      Artifacts:
        Type: 'CODEPIPELINE'
      ServiceRole: 'arn:aws:iam::299199322523:role/iac-demo-code-build-project-service-role'
      Environment: 
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:3.0'
        ComputeType: BUILD_GENERAL1_SMALL
        Type: 'LINUX_CONTAINER'
      Source:
        Type: 'CODEPIPELINE'        
  CBPipeline:        
    Type: AWS::CodePipeline::Pipeline 
    Properties: 
      Name: 'iac-demo-pipeline'
      RoleArn: arn:aws:iam::299199322523:role/service-role/tomcat-web-pipeline-role
      ArtifactStore: 
        Type: S3
        Location: !Ref S3BuildBucket
      Stages: 
        - Name: Source
          Actions:
            - Name: GetSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                  -  Name: Source
              Configuration:
                ConnectionArn: arn:aws:codestar-connections:eu-central-1:299199322523:connection/a7d89539-29f7-4530-b191-92282b663b27
                FullRepositoryId: "sundgaard-aws/simple-java-bootstrap-app"
                BranchName: main
                OutputArtifactFormat: CODE_ZIP
        - Name: Build
          Actions:
            - Name: StartBuild
              InputArtifacts:
                - Name: Source
              ActionTypeId: 
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Built
              Configuration: 
                ProjectName: !Ref CBProject                
        - Name: Deploy
          Actions:
            - Name: StartDeploy
              InputArtifacts:
                - Name: Built
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeploy
              Configuration: 
                ApplicationName: 'iac-demo-app'
                DeploymentGroupName: 'iac-demo-app-dg'
    DependsOn: CBProject 
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
        ApplicationName: 'iac-demo-app'
        ComputePlatform: Server    
  CodeDeployDeploymentGroup: 
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties: 
      DeploymentGroupName: "iac-demo-app-dg"
      ApplicationName: "iac-demo-app"      
      Ec2TagFilters: 
        - Key: "Name"
          Value: "iac-demo-web-ec2"
          Type: "KEY_AND_VALUE"
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties: 
      Path: /
      RoleName: 'iac-demo-code-deploy-service-role'
      AssumeRolePolicyDocument: 
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codedeploy.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"        